Some project refactors
radicle-dev/radicle-interface pull request #201
Opened 2022-02-14 12:33 UTC by sebastinez

Creates a new `Project` class that has some useful static functions, and once created an instance with `Project.get` it allows us to pass the instance through components and have a unified API.

Also removes the `ProjectContentRoutes` and integrates the `Router` into the `View` component.

2022-02-14 12:37 UTC, sebastinez commented on src/base/orgs/View/Projects.svelte
> +  import type { ProjectInfo, Anchor, PendingAnchor } from "@app/base/projects/Project";
Personally I prefer the destructured way of importing, but I left the default `* as proj` imports. Maybe we should define when it makes sense and when not.

2022-02-14 12:39 UTC, sebastinez commented on src/base/orgs/View/Projects.svelte
>    {#await seed.getProjects(profile?.id)}
We have the option to return `Project` instances from this function, similar to the `Org.getMulti` function.
I did not implement it, under the reason that we would be fetching and doing a lot of overhead to get just `projectInfo` and we can leave that for when a user visits the project.

2022-02-15 10:03 UTC, cloudhead requested changes
This is very nice and clean! Left some comments that should make things even tighter.

2022-02-15 10:03 UTC, cloudhead commented on src/base/seeds/Seed.ts
> +import * as proj from '@app/base/projects/Project';
Same comment as below, we shouldn't be importing things between sub-apps (`base/*`), this creates a dependency spaghetti.

2022-02-15 10:03 UTC, cloudhead commented on src/base/projects/Project.ts
> +  info: ProjectInfo;
I would extend `Project` with `ProjectInfo`. Then you can pass `Project` where `ProjectInfo` is expected, eg. BranchSelector.

2022-02-18 10:15 UTC, cloudhead commented on src/base/projects/BranchSelector.svelte
> +  export let project: Project;
Could we not leave this with `ProjectInfo`, since `Project` implements it?

2022-02-18 10:20 UTC, cloudhead approved these changes
Looks great! Just one question.

2022-02-21 21:21 UTC, cloudhead approved these changes
Great, can you squash & rebase?

2022-02-22 12:07 UTC, merged